services:
    mongo: 
        image: mongo # this will be the hostname should be used to communicate with other container
        container_name: mongo
        ports:
            - 27017:27017
        volumes:
            - mongo-db-data:/data/db
        
    http-server:
        container_name: http-server
        build: 
            context: .
            dockerfile: ./docker/Dockerfile.httpServer
        ports:
            - 3000:3000
        depends_on:
            - mongo 
        environment:
            - MONGO_URL=mongodb://mongo:27017/myapp
            - PORT=3000
        
    ws-server:
        container_name: ws-server
        build: 
            context: .
            dockerfile: ./docker/Dockerfile.webSocket 
        ports:
            - 8080:8080
        depends_on:
            - mongo 
    
    frontend: 
        container_name: frontend-server
        build: 
            context:  .
            dockerfile: ./docker/Dockerfile.frontEnd 
        ports:
            - 4173:4173 
         
volumes:
    mongo-db-data: 