# FRONTEND
server {
    listen 80;
    server_name frontend.xode-sumit.me;

    location / {
        proxy_pass http://localhost:4173;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}

# HTTP BACKEND (example)
server {
    listen 80;
    server_name http.xode-sumit.me;

    location / {
        proxy_pass http://localhost:3000;
    }
}

# WEBSOCKET (ws)
server {
    listen 80;
    server_name ws.xode-sumit.me;

    location / {
        proxy_pass http://localhost:8080;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }
}